name: Rust + Tauri CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Upgraded from 16 to 20

    - name: Install Tauri CLI    
      run: npm install -g @tauri-apps/cli  # Correct way to install Tauri

    - name: Install Cargo Tauri CLI (Optional, if needed)
      run: cargo install tauri-cli  # Ensures Rust-side Tauri CLI is installed

    - name: Build for ${{ matrix.os }}
      run: |
        # Set architecture (optional)
        if [ "$RUNNER_OS" == "Linux" ]; then
          export TAURI_TARGET=x86_64-unknown-linux-gnu
        elif [ "$RUNNER_OS" == "Windows" ]; then
          export TAURI_TARGET=x86_64-pc-windows-gnu
        elif [ "$RUNNER_OS" == "macOS" ]; then
          export TAURI_TARGET=x86_64-apple-darwin
        fi

        cargo tauri build --target $TAURI_TARGET

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: editor-${{ matrix.os }}
        path: ./target/release/bundle/**  # Fixed artifact path
