name: Rust + Tauri CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
        include:
          - os: windows-latest
            target: x86_64-pc-windows-gnu
          - os: macOS-latest
            target: x86_64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Tauri CLI
      run: |
        python -m pip install --upgrade pip
        pip install tauri-cli

    - name: Install Dependencies
      run: |
        cargo build --verbose

    - name: Build Tauri App
      env:
        TAURI_PLATFORM: ${{ matrix.target }}
      run: |
        cargo tauri build --target ${{ matrix.target }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-build
        path: ./target/tauri-apps/*
